language: go
before_install:
  - go get github.com/mattn/goveralls@master
install:
  - make deps
script:
  - make pretest
  - make coverage
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://gocenter.io
go:
  - 1.x
